// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJIt8GCmFpYiZmI51qPasMaWv7Y-PQu78',
    appId: '1:357533261210:web:4e7544588fe10423a76e23',
    messagingSenderId: '357533261210',
    projectId: 'expense-manager-6fe68',
    authDomain: 'expense-manager-6fe68.firebaseapp.com',
    storageBucket: 'expense-manager-6fe68.firebasestorage.app',
    measurementId: 'G-XTX6SG3S6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBIA26FuvMoVbpe9cwfiMcNzjcsKTS1bY',
    appId: '1:357533261210:android:311afbdf484935f4a76e23',
    messagingSenderId: '357533261210',
    projectId: 'expense-manager-6fe68',
    storageBucket: 'expense-manager-6fe68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl7U4r7TPJd7DxM_C6gAO4_eOHAV0eONM',
    appId: '1:357533261210:ios:79d70fac153f9029a76e23',
    messagingSenderId: '357533261210',
    projectId: 'expense-manager-6fe68',
    storageBucket: 'expense-manager-6fe68.firebasestorage.app',
    iosClientId: '357533261210-dhriok8fb7k705ofredsmcjj2ek0p136.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl7U4r7TPJd7DxM_C6gAO4_eOHAV0eONM',
    appId: '1:357533261210:ios:79d70fac153f9029a76e23',
    messagingSenderId: '357533261210',
    projectId: 'expense-manager-6fe68',
    storageBucket: 'expense-manager-6fe68.firebasestorage.app',
    iosClientId: '357533261210-dhriok8fb7k705ofredsmcjj2ek0p136.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseManager',
  );
}
